name: cobonno
description: Cobonno
version: 1.0.0+2
publish_to: none

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  auto_route: ^5.0.4
  firebase_core: ^2.7.1
  carousel_slider: ^4.1.1
  sizer: ^2.0.15
  intl_phone_field: ^3.1.0
  pin_code_fields: ^7.4.0
  firebase_auth: ^4.2.5
  loader_overlay: ^2.0.7
  cloud_firestore: ^4.3.1
  flutter_spinkit: ^5.1.0
  cached_network_image: ^3.2.1
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutter_web_frame: ^0.0.3
  webview_flutter: ^3.0.0
  age_calculator: ^1.0.0
  image_picker: ^0.8.5+3
  firebase_storage: ^11.0.10
  cloud_functions: ^4.0.7
  flutter_emoji: ^2.4.0
  font_awesome_flutter: ^10.3.0
  image_picker_for_web: ^2.1.8
  photo_gallery: ^1.1.1
  permission_handler: ^10.0.0
  photo_manager: ^2.4.1
  pinch_zoom: ^1.0.0
  camera: ^0.10.0
  video_player: ^2.4.5
  path_provider: ^2.0.11
  provider: ^6.0.3
  photofilters: ^3.0.1
  image: ^3.2.0
  hashtagable: ^2.1.0
  http: ^0.13.4
  google_sign_in: ^5.4.0
  firebase_remote_config: ^3.0.9
  flutter_facebook_auth: ^5.0.7
  twitter_login: ^4.2.3
  like_button: ^2.0.4
  edge_detection: ^1.1.1
  path: ^1.8.2
  firebase_auth_platform_interface: ^6.4.0
  device_info_plus: ^8.0.0
  date_time_picker: ^2.1.0
  heic_to_jpg: ^0.2.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5
  firebase_crashlytics: ^3.0.11
  firebase_dynamic_links: ^5.0.11
  firebase_messaging: ^14.2.1
  sliding_up_panel: ^2.0.0+1
  multi_image_crop: ^0.0.2
  image_cropper: ^3.0.0
  delayed_display: ^2.0.0
  media_store_plus: ^0.0.5

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/appIcon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
  fonts:
    - family: KozGoPr6N
      fonts:
        - asset: fonts/KozGoPr6N-Regular.otf
        - asset: fonts/KozGoPr6N-Bold.otf
          weight: 700
